parameters:
  ckeditor_tags: "<p><br><span><h1><h2><h3><h4><a>
  <img><figure><figcaption>
  <ul><ol><li>
  <strong><b><em><u><s><sup><sub><pre>
  <table><tbody><thead><tr><td><th><caption>
  <ltb-abbr><div><symbol>"

fos_ck_editor:
  autoload: false
  default_config: ltb_config
  configs:
    ltb_config: &ckeditor_default
      language: "en"
      toolbar: "ltb_toolbar"
      filebrowserBrowseRoute: "elfinder"
      format_tags: "p;h1;h2;citation;reference"
      extraPlugins: "latexeditor,image2"
      extraAllowedContent: "figure(latex-figure);figcaption(latex-caption);img(latex-image);a[data-concept-id](concept-link);ltb-abbr[data-abbr-id];symbol"
      removePlugins: "dialogadvtab"
      bodyClass: "ltb-text-container"
    ltb_no_image:
      <<: *ckeditor_default
      removeButtons: "Image"
    ltb_concept_config:
      <<: *ckeditor_default
      extraPlugins: "image2,latexeditor,abbreviationselector,conceptselector,ltbbuttons"
  toolbars:
    configs:
      ltb_toolbar: [ "@text_tools", "@ltb_tools", "/", "@font_tools", "@edit_tools" ]
    items:
      edit_tools: [ "Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "RemoveFormat" ]
      text_tools: [ "Highlight", "Symbol", "Subscript", "Superscript", "-", "NumberedList", "BulletedList", "-", "Table" ]
      ltb_tools:  [ "Image", "LatexEditor", "ConceptSelector", "AbbreviationSelector" ]
      font_tools: [ "Format", "TextColor" ]
  plugins:
    latexeditor:
      path:     "/ckeditor-plugins/latexeditor/"
      filename: "plugin.js"
    image2:
      path:     "/ckeditor-plugins/image2/"
      filename: "plugin.js"
    abbreviationselector:
      path:     "/ckeditor-plugins/abbreviationselector/"
      filename: "plugin.js"
    conceptselector:
      path:     "/ckeditor-plugins/conceptselector/"
      filename: "plugin.js"
    ltbbuttons:
      path:     "/ckeditor-plugins/ltbbuttons/"
      filename: "plugin.js"
