framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: ~
  #http_method_override: true

  session:
    # With this config, PHP's native session handling is used
    handler_id: ~

  assets:
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

  #esi: ~
  #fragments: ~
  php_errors:
    log: true
