ivory_ck_editor:
  autoload: false
  default_config: default
  configs:
    default:
      filebrowserBrowseRoute: "elfinder"
      extraPlugins: "latexeditor"
  plugins:
    latexeditor:
      path:     "/ckeditor-plugins/latexeditor/"
      filename: "plugin.js"
