nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: [ ]
    allow_methods: [ ]
    allow_headers: [ ]
    expose_headers: [ ]
    max_age: 0
  paths:
    '^/api/(?!doc)':
      allow_origin: [ '*' ]
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      allow_headers: [ 'Content-Type', 'X-LTB-AUTH' ]
      max_age: 3600
