security:
  # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    default_provider:
      id: App\Security\UserProvider

  access_decision_manager:
    strategy: unanimous

  encoders:
    App\Entity\User:
      algorithm: bcrypt

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      oidc:
        default_target_path: /
        always_use_default_target_path: true
        check_path: login_check
        login_path: login
      form_login:
        default_target_path: /
        always_use_default_target_path: true
        check_path: login_check
        login_path: login
        username_parameter: "login[_username]"
        password_parameter: "login[_password]"
      logout:
        path:   logout
        target: _home

  access_control:
    - { path: ^/_wdt/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_profiler/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
    - { path: ^/login.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
