security:
  # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    default_provider:
      id: App\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      oidc: ~
      anonymous: true
      logout:
        path:   logout
        target: _home

  access_control:
    - { path: ^/_wdt/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/_profiler/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
    - { path: ^/login.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
