sentry:
  dsn: ~
  options:
    release: '%sentry_release%'
    excluded_exceptions:
      - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
      - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
      - Symfony\Component\Security\Core\Exception\AccessDeniedException
