swiftmailer:
  default_mailer: default
  mailers:
    default:
      url: '%env(MAILER_URL)%'
      spool: { type: memory }
    exception_mailer:
      url: '%env(EXCEPTION_MAILER_URL)%'
      spool: { type: memory }
