twig:
  paths: [ '%kernel.project_dir%/templates' ]
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - "_form/form_layout.html.twig"
  globals:
    allowed_ckeditor_tags: '<p><br>'
