twig:
  paths: [ '%kernel.project_dir%/templates' ]
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - "_form/form_layout.html.twig"
    - "_form/_button_layout.html.twig"
    - "_form/_collection_layout.html.twig"
    - "_form/_download_preview_layout.html.twig"
    - "_form/_learning_paths_layout.html.twig"
    - "_form/_custom_types_layout.html.twig"
  globals:
    allowed_ckeditor_tags: '%ckeditor_tags%'
