stages:
  - prepare
  - lint
  - build
  - tests
  - sentry
  - deploy

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/symfony/install-dependencies.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/yarn/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/shell/shellcheck.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/ts/tslint.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/yaml/yamllint.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/sass/sasslint.yml'

  # Build
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/yarn/build-prod.yml'

  # Tests
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/php/phpunit.yml'
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/symfony/check-security.yml'

  # Sentry
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/sentry/sentry.yml'

  # Deploy
  - project: 'intern/runner-templates'
    ref: "2.0"
    file: '/deploy/deploy.yml'

install-dependencies:
  artifacts:
    paths:
      # Default paths from this stage. If you need more, make sure to copy these in your build step
      - assets/js/_fos_routes.json
      - vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js
      - vendor/drenso/symfony-shared/src/Resources/translations
      - .secrets.json
      # Extra paths
      - assets/js/_fos_js_routes.js

js-analysis:
  stage: lint
  image:
    name: hyzual/jshint:latest
    entrypoint: [ "" ]
  needs: []
  before_script:
    - cp tests/jshint/.jshintignore .
  script:
    - /usr/bin/jshint src --verbose --config tests/jshint/config
  tags:
    - docker
  except:
    - master
    - production

action-security-check:
  script:
    - php bin/console ltb:check:action-security
