api_study_area_list:
  path: /api/studyarea
  controller: App\Api\Controller\StudyAreaController::list
  schemes: [ https ]
  methods: GET

api_controllers:
  type: annotation
  resource: ../../src/Api/Controller/
  schemes: [ https ]
  prefix: /api/studyarea/{_studyArea}
  requirements:
    _studyArea: \d+

_api_catch_all:
  path: /api/{slug}
  controller: App\Api\Controller\DefaultController::notFound
  requirements:
    slug: .+
