# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  kickin.exceptionhandler.configuration.class: App\ExceptionHandler\ExceptionHandlerConfiguration
  app_version: "%env(APP_VERSION)%"
  production_server: "%env(PRODUCTION_SERVER)%"
  exception_receiver: "%env(EXCEPTION_RECEIVER)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true    # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false     # Allows optimizing the container by removing unused services; this also means
              # fetching services directly from the container via $container->get() won't work.
              # The best practice is to be explicit about your dependencies anyway.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  # Overwrite for JMS serializer to always use the identical names
  jms_serializer.naming_strategy:
    alias: jms_serializer.identical_property_naming_strategy

  App\Database\SoftDeletableSubscriber:
    tags:
      - { name: doctrine.event_subscriber, connection: default }
